// Keyword rules that sort bank descriptions into categories. First match wins.
// Add your own shops here as you spot them in your statements.
const RULES: [string, RegExp][] = [
  ["transfer", /\b(TFR|TRANSFER|TO A\/C|FROM A\/C|SAVINGS|ISA)\b/i],
  ["salary", /\b(SALARY|WAGES|PAYROLL|PAYE)\b/i],
  ["debt", /\b(KLARNA|CLEARPAY|PAYPAL CREDIT|BARCLAYCARD|AMEX|AMERICAN EXPRESS|CAPITAL ONE|VANQUIS|AQUA|LOAN|FINANCE|CREDIT CARD|STUDENT LOANS? CO)\b/i],
  ["rent", /\b(RENT|LETTING|LETTINGS|ESTATES|PROPERTY|MORTGAGE|ACCOMMODATION|UNITE STUDENTS)\b/i],
  ["bills", /\b(COUNCIL|EE\b|VODAFONE|O2|THREE|GIFFGAFF|VIRGIN|BT\b|SKY|OCTOPUS|BRITISH GAS|EDF|E\.ON|OVO|WATER|TV LICENCE|INSURANCE|NETFLIX|SPOTIFY|APPLE\.COM|GOOGLE|AMAZON PRIME|DISNEY|ICLOUD|GYM|PUREGYM|THE GYM)/i],
  ["transport", /\b(TFL|TRAINLINE|UBER|BOLT|NATIONAL RAIL|LNER|AVANTI|GWR|NORTHERN|ARRIVA|STAGECOACH|FIRST BUS|NATIONAL EXPRESS|SHELL|ESSO|BP\b|TEXACO|PARKING|RINGGO|DVLA)/i],
  ["food", /\b(TESCO|SAINSBURY|ASDA|ALDI|LIDL|MORRISONS|CO-OP|COOP|WAITROSE|ICELAND|M&S|MARKS|GREGGS|MCDONALD|KFC|SUBWAY|NANDO|DOMINO|PIZZA|DELIVEROO|JUST EAT|UBER EATS|STARBUCKS|COSTA|PRET|CAFE|RESTAURANT|BURGER|TAKEAWAY)/i],
  ["shopping", /\b(AMAZON|AMZN|EBAY|ARGOS|PRIMARK|NEXT|ZARA|H&M|JD SPORTS|SPORTS DIRECT|BOOTS|SUPERDRUG|CURRYS|IKEA|SHEIN|ASOS|TEMU|VINTED)/i],
  ["fun", /\b(CINEMA|ODEON|VUE|CINEWORLD|STEAM|PLAYSTATION|XBOX|NINTENDO|TICKETMASTER|PUB|BAR\b|CLUB)/i],
];

export function categorize(description: string, isIncome: boolean): string {
  for (const [cat, re] of RULES) {
    if (!re.test(description)) continue;
    if (isIncome && !["salary", "transfer"].includes(cat)) return "other";
    return cat;
  }
  return "other";
}
